name: build
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target: [ linux.amd64, linux.arm64, darwin.amd64, windows.amd64 ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16.0
      - name: build
        env:
          target: ${{ matrix.target }}
        run: |
          os=$(echo $target | awk -F. '{print $1}')
          arch=$(echo $target | awk -F. '{print $2}')
          ./build.sh $os $arch
